namespace Catglobe.ResXFileCodeGenerator.Tests;

public class HelperGeneratorTests
{
    [Fact]
    public void CanGenerateCombo()
    {
        var (generatedFileName, sourceCode, errorsAndWarnings) = new StringBuilderGenerator()
            .Generate(
                combo: new(
	                new ResxGroup([
		                ResxFile.From(new AdditionalTextStub("test.resx", ""))!,
		                ResxFile.From(new AdditionalTextStub("test.da.resx", ""))!,
		                ResxFile.From(new AdditionalTextStub("test.da-dk.resx", ""))!,
	                ]).SubFiles.CultureInfos),
                cancellationToken: default
            );
        var expected = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Catglobe.ResXFileCodeGenerator;
internal static partial class Helpers
{
    public static string GetString_1030_6(string fallback, string da_dk, string da) => global::System.Globalization.CultureInfo.CurrentUICulture.LCID switch
    {
        1030 => da_dk,
        6 => da,
        _ => fallback
    };
}
";
        errorsAndWarnings.ShouldBeEmpty();
        generatedFileName.ShouldBe("Catglobe.ResXFileCodeGenerator.1030_6.g.cs");
        sourceCode.ShouldBeEquivalentTo(expected);
    }
    [Fact]
    public void CanGenerateEmptyCombo()
    {
        var (generatedFileName, sourceCode, errorsAndWarnings) = new StringBuilderGenerator().Generate(new CultureInfoCombo([]), default);
        var expected = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Catglobe.ResXFileCodeGenerator;
internal static partial class Helpers
{
    public static string GetString_(string fallback) => global::System.Globalization.CultureInfo.CurrentUICulture.LCID switch
    {
        _ => fallback
    };
}
";
        errorsAndWarnings.ShouldBeEmpty();
        generatedFileName.ShouldBe("Catglobe.ResXFileCodeGenerator..g.cs");
        sourceCode.ShouldBe(expected);
    }
}
